equinix/terraform-provider-equinix

.github/workflows/release.yml
.goreleaser.yml
.travis.yml

Introduced release automation with github actions and goreleaser, as advised on [Publishing Providers page](https://www.terraform.io/docs/registry/providers/publishing.html).
I've also used configs from [Packet Terrafrom provider repo](https://github.com/packethost/terraform-provider-packet).
* added release action with goreleaser for v* tags
* modified travis config to forbid double builds on PRs by limiting builds to master branch
Above requires GPG_PRIVATE_KEY and PASSPHRASE to be configured as repo secrets, what was also done.
Key for signing releases was created (however it uses my mail due to lack of generic one). Nevertheless it is separate key from my private one.

Add release automation with actions and goreleaser

---

docs/resources/network_bgp.md
equinix/provider_test.go
equinix/resource_network_bgp.go
equinix/resource_network_bgp_acc_test.go

@ocobleseqx I've made `authentication_key` field **optional** + updated acceptance test, so in first step it creates BGP peering config **without** `authentication_key`. I've also added second step that updates existing BGP peering with a new auth key.

Ref #28 network bgp authenticationKey is optional

---

.github/workflows/release.yml
.travis.yml

Go 1.16 adds support for darwin-arm64 binaries, might as well go all the way to the latest version.
I believe this should fix #51, but I don't know if there's other parts of your release pipeline.
I've run the unit tests with Go 1.17 locally, and I've also run goreleaser with Go 1.17 and without changing the config it already created darwin-arm64 binaries.
I have not run the acceptance tests, since I don't have a test environment to run them against.

Use Go 1.17 in CI

---

DEVELOPMENT.md
equinix/resource_ecx_l2_connection.go
equinix/resource_ecx_l2_connection_acc_test.go
equinix/resource_ecx_l2_connection_test.go

This change provides consistency between terraform provider and upstream API and push up https://github.com/equinix/terraform-provider-equinix/pull/64
- This PR includes: 
- Actions attribute definition
- Unit testing for TestFabricL2Connection_flattenActions function
- Updated AWS connection Acceptance test

Add Actions attribute on equinix_ecx_l2_connection

---

equinix/config.go
equinix/provider.go
equinix/provider_test.go
equinix/resource_ecx_l2_connection.go
equinix/resource_ecx_l2_connection_accepter_test.go
equinix/resource_ecx_l2_connection_test.go
equinix/resource_ecx_l2_serviceprofile.go
equinix/resource_ecx_l2_serviceprofile_test.go
equinix/resource_network_acl_template.go
equinix/resource_network_acl_template_test.go
equinix/resource_network_bgp.go
equinix/resource_network_bgp_test.go
equinix/resource_network_device.go
equinix/resource_network_device_acc_test.go
equinix/resource_network_device_link_test.go
equinix/resource_network_device_test.go
equinix/resource_network_ssh_key.go
equinix/resource_network_ssh_key_test.go
equinix/resource_network_ssh_user_test.go

Fixes #84 
With the fix below it will check the status of the secondary connection for redundant connections. It usually sets the status of the primary and secondary connections at the same time, but there is no other way to make sure there is no race condition than to also check the status of the secondary connection.
https://github.com/equinix/terraform-provider-equinix/blob/3843c8408eeec9c536a440f947d50366b5745af7/equinix/resource_ecx_l2_connection.go#L488-L500
All other changes included are forced code style formatting

Added waiter for secondary connection. resolves #84

---

docs/resources/ecx_l2_serviceprofile.md
equinix/provider.go
equinix/resource_ecx_l2_serviceprofile.go
equinix/resource_ecx_l2_serviceprofile_acc_test.go
equinix/resource_ecx_l2_serviceprofile_test.go

Issue #88 
As described in the issue Terraform detectes some changes since the last "terraform apply". 
First one refers to param private_user_emails, since API returns normalized list with lowercase values. 
```
~ private_user_emails = [
- "John.Doe@example.com",
- "Marry.Doe@example.com",
+ "john.doe@example.com",
+ "marry.doe@example.com",
]
```
To verify that this is the case I added a slicesMatchCaseInsensitive function and if so, then we just keep value of previous schema.
https://github.com/equinix/terraform-provider-equinix/blob/f45be6043d7fdf566ae67226e7d60cf52f290692/equinix/resource_ecx_l2_serviceprofile.go#L543-L550
Second issue referes to features. TestProfile is a legacy API parameter that is no longer required and always returns False even if user set True.
```
+ features { …
```

Fix resource_ecx_l2_serviceprofile detecting diff after refresh

---

equinix/resource_network_device.go
equinix/resource_network_device_acc_test.go

- Removed condition of int >= 1 for AdditionalBandwidth 
- Updated r/network_device acceptance tests to validate additional_bandwidth attribute equal 0
```
ubuntu@docker: export TESTS_REGEXP="TestAccNetworkDevice_CSR1000V_HA_Managed_Sub"
ubuntu@docker: make testacc
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test $(go list ./... |grep -v 'vendor') -v -count 1 -parallel 20 -run='TestAccNetworkDevice_CSR1000V_HA_Managed_Sub' -timeout 180m
?       github.com/equinix/terraform-provider-equinix   [no test files]
=== RUN   TestAccNetworkDevice_CSR1000V_HA_Managed_Sub
=== PAUSE TestAccNetworkDevice_CSR1000V_HA_Managed_Sub
=== CONT  TestAccNetworkDevice_CSR1000V_HA_Managed_Sub
--- PASS: TestAccNetworkDevice_CSR1000V_HA_Managed_Sub (2273.70s)
PASS
ok …
```

fixes #69 Allow value 0 for additional bandwidth

---

docs/index.md
equinix/config.go
equinix/provider.go
equinix/provider_test.go
go.mod

This PR investigates what it would look like to support API sandbox / playground tokens:
These can be found in the developer app dashboard: _developer.equinix.com/user/{your id}/apps?refresh_pg_token=true_
I'm not sure if the sandbox provides the necessary state consistency to allow for the acceptance tests to pass.
If _some_ acceptance tests can pass with the playground, we could introduce levels of acceptance testing, gated by environment variables, that cover what is possible.
To test:
```
export EQUINIX_API_ENDPOINT=https://playgroundapi.equinix.com
export EQUINIX_API_TOKEN=..........
make testacc
```
---
I ran into `unsupported state format version: expected "0.1", got "0.2"` and had to address that by updating the version of the TF SDK: …

add support for running acceptance tests with sandbox/playground tokens

---

cmd/migration-tool/main.go
docs/resources/equinix_ecx_l2_connection.md
docs/resources/equinix_metal_device.md
equinix/resource_ecx_l2_connection.go
equinix/resource_ecx_l2_connection_acc_test.go
equinix/resource_ecx_l2_connection_test.go
go.mod
go.sum

**Description:** 
Field `RedundantUUID` was used to check if there was a secondary connection. This field is not been returned for new connections anymore. This field can be deleted from the schema but then it will be required a full scan for all connections in the read function to ensure the `terraform import` command works also for redundant connections.
From [terraform import function docs](https://www.terraform.io/plugin/sdkv2/resources/import): 
> This function requires the Read function to be able to refresh the entire resource with d.Id() ONLY
Without `redundantUUID` field returned from the API there is no way to know if it is a redundant connection just with the primary connection ID, since all connections both single and redundant have a `redundancyGroup`. Therefore it will be …

fix delete and import for redundant l2 connections

---

equinix/resource_network_device.go

Since hostname prefix length check is not the same for different vendors, there is no single length range which could apply to all the vendors. We will remove validation from terraform side and purely rely on the API side validation for that field.
This PR also fix https://github.com/equinix/terraform-provider-equinix/issues/118.

NFV-18966, NFV-18994: remove hostname validation and fix acl issues in device deletion flow

---

docs/resources/equinix_network_acl_template.md

`equinix_network_acl_template` docs was in the metal subcategory. Now it will appear in the Network Edge section of terraform regisitry
fixes https://github.com/equinix/terraform-provider-equinix/issues/127

change equinix_network_acl_template docs  subcategory to network edge

---

docs/data-sources/equinix_metal_connection.md
docs/resources/equinix_metal_connection.md
docs/resources/equinix_metal_device.md
docs/resources/equinix_metal_reserved_ip_block.md
docs/resources/equinix_metal_spot_market_request.md
equinix/data_source_metal_connection.go
equinix/data_source_metal_ip_block_ranges_acc_test.go
equinix/data_source_metal_reserved_ip_block.go
equinix/data_source_metal_reserved_ip_block_acc_test.go
equinix/data_source_metal_vlan_acc_test.go
equinix/helpers_device.go
equinix/helpers_device_test.go
equinix/resource_metal_connection.go
equinix/resource_metal_connection_acc_test.go
equinix/resource_metal_device.go
equinix/resource_metal_device_network_type.go
equinix/resource_metal_gateway.go
equinix/resource_metal_ip_attachment_acc_test.go
equinix/resource_metal_port_vlan_attachment_acc_test.go
equinix/resource_metal_project_api_key_acc_test.go
equinix/resource_metal_project_ssh_key_acc_test.go
equinix/resource_metal_reserved_ip_block.go
equinix/resource_metal_reserved_ip_block_acc_test.go
equinix/resource_metal_spot_market_request_acc_test.go
equinix/resource_metal_vrf_acc_test.go
equinix/utils.go

sync equinix(v1.6.0-alpha.3) and metal(v3.3.0-alpha.3) providers

---

equinix/data_source_metal_connection.go
go.mod
go.sum

Added validation to check expires_at is not null before converting Timestamp to string
Bug fix https://github.com/equinix/terraform-provider-equinix/issues/147
Packngo version update required to v0.25.0

resource/datasource equinix_metal_connection service_token expires_at can be null

---

go.mod
go.sum

Dependabot reported this but could not create the PR.
> The Hashicorp go-getter library before 1.5.11 could write SSH credentials into its logfile, exposing sensitive credentials to local users able to read the logfile.

update go-getter to 1.5.11 for CWE-532

---

equinix/data_source_metal_device_acc_test.go
equinix/data_source_metal_ip_block_ranges_acc_test.go
equinix/data_source_metal_port_acc_test.go
equinix/data_source_metal_precreated_ip_block_acc_test.go
equinix/resource_metal_bgp_setup_acc_test.go
equinix/resource_metal_connection.go
equinix/resource_metal_device.go
equinix/resource_metal_device_acc_test.go
equinix/resource_metal_ip_attachment_acc_test.go
equinix/resource_metal_port_acc_test.go
equinix/resource_metal_port_vlan_attachment_acc_test.go
equinix/resource_metal_project_ssh_key_acc_test.go
equinix/resource_metal_reserved_ip_block_acc_test.go

PR transferred from https://github.com/equinix/terraform-provider-metal/pull/190
> [t0mk](https://github.com/t0mk) commented [on 10 Sep 2021](https://github.com/equinix/terraform-provider-metal/pull/190#issue-993027922)
This PR adds termination_time to all the relevant metal_device resources in provider acceptance tests. Fixes https://github.com/equinix/terraform-provider-equinix/issues/166
Signed-off-by: Tomas Karasek [tom.to.the.k@gmail.com](mailto:tom.to.the.k@gmail.com)

add termination_time to metal_device resources in acceptance

---

docs/data-sources/equinix_metal_connection.md
docs/resources/equinix_metal_vrf.md
equinix/data_source_metal_connection.go
equinix/data_source_metal_facility_acc_test.go
equinix/data_source_metal_gateway_acc_test.go
equinix/data_source_metal_organization.go
equinix/data_source_metal_spot_market_price_acc_test.go
equinix/data_source_metal_spot_market_request_acc_test.go
equinix/data_source_metal_vlan_acc_test.go
equinix/data_source_network_device.go
equinix/data_source_network_device_test.go
equinix/helpers_device_test.go
equinix/resource_metal_bgp_setup_acc_test.go
equinix/resource_metal_connection.go
equinix/resource_metal_connection_acc_test.go
equinix/resource_metal_device_acc_test.go
equinix/resource_metal_device_network_type.go
equinix/resource_metal_gateway_acc_test.go
equinix/resource_metal_organization.go
equinix/resource_metal_port_acc_test.go
equinix/resource_metal_port_vlan_attachment_acc_test.go
equinix/resource_metal_project_ssh_key_acc_test.go
equinix/resource_metal_reserved_ip_block_acc_test.go
equinix/resource_metal_spot_market_request_acc_test.go
equinix/resource_metal_virtual_circuit_acc_test.go
equinix/resource_metal_vrf_acc_test.go
equinix/resource_network_device.go

Sync https://github.com/equinix/terraform-provider-metal/pull/223
- Always return project_id specified in the schema (to cover dedicated connection without project), and later for shared connections check project assigned to the virtual circuit.
- Allow retrieve existing connections created through the portal with speed value 0.
- Sort ports by role , asserting the API always returns primary for len of 1 responses (to replicate current provider equinix behavoir)
- Solved r/equinix_metal_connection producing non-empty plan after apply if type is dedicated (More details https://github.com/equinix/terraform-provider-metal/issues/222)
- Fix https://github.com/equinix/terraform-provider-equinix/issues/144

r/ds equinix_metal_connection fixed and sync behavoir with terraform-provider-metal

---

equinix/resource_metal_gateway.go
equinix/resource_metal_virtual_circuit.go
equinix/resource_metal_virtual_circuit_acc_test.go

`ignoreResponseErrors` after `deleteWaiter.WaitForState` for both gw and vc was taking a previous http response an not the one coming from the last API request originated in the WaitForState `Refresh` function. `ignoreResponseErrors` functions (`httpForbidden`, `httpNotFound`,...) check the http StatusCode if the response arg is not `nil`, otherwise they check the error arg and see if it is of type `packngo.ErrorResponse` and then get the `StatusCode` from the error.
~`if ignoreResponseErrors(httpForbidden, httpNotFound)(resp, err)`~
`if ignoreResponseErrors(httpForbidden, httpNotFound)(nil, err)`

Fix gateway and vc delete waiting

---

docs/data-sources/equinix_metal_virtual_circuit.md
equinix/data_source_metal_virtual_circuit.go

This PR adds missing `connection_id` in data source `equinix_metal_virtual_circuit`
All data source using same read function than their matching resource must have same schema keys or it [will produce an error in the d.Set(key, value) function if the key is invalid.](https://pkg.go.dev/github.com/hashicorp/terraform/helper/schema#ResourceData.Set
) 
This error was found in the equinix metal provider: https://github.com/equinix/terraform-provider-metal/runs/7204768928?check_suite_focus=true#step:5:629

fix missing attribute connection_id in ds equinix_metal_virtual_circuit

---

docs/resources/equinix_ecx_l2_connection.md
docs/resources/equinix_metal_connection.md
equinix/resource_ecx_l2_connection.go
equinix/resource_ecx_l2_connection_acc_test.go
equinix/resource_ecx_l2_connection_test.go
go.mod
go.sum

Feature required to support z-side service token.
This field is documented at 
https://docs.equinix.com/en-us/Content/Interconnection/Fabric/service%20tokens/Fabric-Service-Tokens.htm#:~:text=requirements%20per%20provider.-,Z%2DSide%20Service%20Tokens,-If%20you%20want
And
https://developer.equinix.com/docs/fabric-connect-using-service-token-parameters-mapping
Depends on https://github.com/equinix/ecx-go/pull/8: already merged and included in new release https://github.com/equinix/ecx-go/releases/tag/v2.3.0
Fix https://github.com/equinix/terraform-provider-equinix/issues/223

add attribute zside_service_token to equinix_ecx_l2_connection

---

docs/data-sources/equinix_metal_connection.md
docs/guides/equinix_fabric_cloud_providers.md
docs/resources/equinix_metal_connection.md
equinix/data_source_metal_connection.go
equinix/resource_metal_connection.go
examples/connectivity/README.md
examples/connectivity/alibaba-cloud-connection/README.md
examples/connectivity/aws-connection/README.md
examples/connectivity/azure-connection/README.md
examples/connectivity/equinix-metal-to-fabric-connection/README.md
examples/connectivity/gcp-connection/README.md
examples/connectivity/ibm-cloud-connection/README.md
examples/connectivity/oracle-cloud-connection/README.md

This PR includes: 
- Set deprecated token field description in equinix_metal_connection schema and set legacy example back in the documentation. Fix #226
- Update connectivity examples available in github and the equinix_metal_connection documentation to link available Equinix Fabric terraform modules
- Update the list of the available modules in the `Connecting to the cloud with Equinix Fabric via Terraform` guide

Modules and service token documentation

---

docs/resources/equinix_network_acl_template.md
equinix/resource_network_acl_template.go
equinix/resource_network_acl_template_acc_test.go
equinix/resource_network_acl_template_test.go
go.mod
go.sum

As part of August release, we add a description field for each inbound rule of acl template. We want to add that field as part of terraform script as well.
This description field will always be optional and the field length should not be longer than 200 characters.
It will be part of create/update request. It will also be part of get response.
Sample payload as follows:
```
"inboundRules": [
{
"description": "description of the rule",
"protocol": "TCP",
"srcPort": "any",
"dstPort": "any",
"subnet": "216.221.225.13/32",
"seqNo": 1
},
{
"protocol": "TCP",
"srcPort": "53",
"dstPort": "any",
"subnet": "1.1.1.1/32",
"seqNo": 2
}
]
```

NFV-19565: add description field for the acl template inbound rule

---

equinix/resource_metal_device.go
equinix/resource_metal_device_acc_test.go

Create and Delete functions were already checking for 404s/403s, however it may occur a device is in failed state for external changes from the portal or any way out of terraform, returning a 403s in a refresh/plan/apply (read) action. 
Added 403 check on read function and to remove resource from terraform state without errors. It will also check isNewResource to prevent the terraform import from failing silently.
Added a mock for packngo.DeviceService, with only implementation of the GET method.  Other methods can be implemented gradually in the future according to the tests needs.
Fix https://github.com/equinix/terraform-provider-equinix/issues/233

check for forbidden in equinix_metal_device read

---

equinix/resource_metal_device.go

metal device operating_system should only be forcenew when reinstall is not enabled

---

equinix/resource_metal_device.go
go.mod
go.sum

Note: Depends on https://github.com/packethost/packngo/pull/345 and this draft is pointing to the last commit. Module dependency must be updated with the latest release before merge.
Reinstalling option was not taking the new value for `operating_system` since it must be specified in the action request instead of updating it previously

added missed OperatingSystem field to reinstall device

---

docs/resources/equinix_metal_connection.md
equinix/resource_metal_connection.go

Allow to not define `service_token_type` for shared connections in organizations where service token is not enabled.
Fix https://github.com/equinix/terraform-provider-equinix/issues/246

remove check of tokenTypeOk to support legacy fabric connections

---

equinix/data_source_metal_organization.go

The organization data source does not support filtering organizations by address, so the address field (and all nested fields within it) should not have the `Optional` flag set.  This removes the flag so that the organization data source schema matches the behavior.
Fixes #151.

Remove optional flag for address fields in organization data source

---

docs/data-sources/equinix_metal_ip_block_ranges.md
docs/data-sources/equinix_metal_precreated_ip_block.md
docs/data-sources/equinix_metal_reserved_ip_block.md
equinix/data_source_metal_ip_block_ranges.go
equinix/data_source_metal_precreated_ip_block.go
equinix/data_source_metal_precreated_ip_block_acc_test.go
equinix/data_source_metal_reserved_ip_block.go
equinix/resource_metal_reserved_ip_block.go

- `equinix_metal_reserved_ip_block`:
Public IPv4 blocks auto-assigned (management subnets) to a device cannot be retrieved. This PR updates failing test and improve documentation.
- `equinix_metal_reserved_ip_block`, `equinix_metal_ip_block_ranges`:
`metro` is nil for some IP blocks. For those cases `metro` will be retrieved from the `facilitiy`
- update docs
Fix #243

update metal ip resources to retrieve metro from facility if metro is null

---

equinix/data_source_metal_connection.go
equinix/data_source_metal_connection_acc_test.go
equinix/resource_metal_connection.go

This updates the `metal_connection` resource and data source to read the value of `vlans` from the API response to ensure that terraform state stays up-to-date with the real infrastructure if someone modifies the VLANs for a terraform-managed `metal_connection` outside of terraform.
Closes #270

Keep value of metal_connection.vlans in sync with API

---

.github/workflows/acctest.yml

Test sweeper is [failing](https://github.com/equinix/terraform-provider-equinix/actions/runs/3588142143/jobs/6039220202#step:6:227) after introducing new Terratest acc test of `tests` folder.  Terratest does not include [sweeper flags](https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/resource/testing.go#L48-L50).
This change just remove checking of test under `tests` folder but doesn't introduce an alternative solution to prevent failed tests leave active resources, I will open a new issue to find a global solution to cover all acceptance tests

limit sweeper to equinix folder

---

CHANGELOG.md
equinix/config.go

Fix wrong Fabric client credentials validation/configuration introduced in v.1.11.0
Fix #282
https://github.com/equinix/terraform-provider-equinix/discussions/280#discussioncomment-4287845

configure tokensource only if client id/secret are set

---

docs/resources/equinix_metal_device.md
equinix/resource_metal_device.go
equinix/resource_metal_device_acc_test.go

By default, we force recreation of Equinix Metal devices when the `user_data` or `custom_data` attributes change, but this decision only exists within the terraform provider; the Equinix Metal API will happily accept updates to those fields without deleting a device.
Previously we had narrow support to bypass this behavior with a `reinstall` block, but that still involves downtime.  This adds support for `behavior.allow_changes`, which is a list of attributes that are allowed to change _without_ forcing device recreation.
Closes #159

Allow updating some `equinix_metal_device` fields without recreating the instance

---

equinix/resource_metal_device_acc_test.go

Some decommissioned data centers are still included in the list of available facilities for the account used by our tests.  To avoid using these data centers in the meantime, this updates the tests to explicitly remove them from any plans.

Avoid deploying to decommissioned facilities in tests

---

docs/resources/equinix_network_device.md
docs/resources/equinix_network_ssh_key.md
equinix/resource_network_ssh_key.go
equinix/resource_network_ssh_key_acc_test.go
equinix/resource_network_ssh_key_test.go
go.mod
go.sum

In Feb release, we onboarded Arista router in our market place, but only DSA public key is accepted for this vendor. To accommodate this, a new field keyType is introduced when creating a new public key. To support backward compatibility, this new field will be marked as optional and the default value would be RSA in this case. All existing public key that we have in production is RSA key and we migrate those keys to be RSA.
More details could be found in our API documentation.
reference: https://developer.equinix.com/docs?page=/dev-docs/ne/overview

NFV-23884: add public key type field in ssh key resource to onboard Arista device type

---

.goreleaser.yml

We have not been properly injecting the release version into the ProviderVersion constant, so we cannot see terraform provider usage by version at the moment.  This updates the goreleaser config to specify the full import path to the ProviderVersion constant so that the release version ends up where we need it.

Specify full import path to the ProviderVersion constant

---

equinix/resource_metal_device_acc_test.go

While the `termination_time` attribute is supported for on-demand instances, the API currently cannot include that attribute in responses for on-demand devices (even with an `include` parameter, the API will not return that attribute).
This updates the failing device import test to ignore the `termination_time` attribute.  When the API adds support for this attribute in responses for on-demand devices, we can update the test to once again expect the imported `termination_time` attribute to match state.

ci: ignore missing termination_time since API doesn't provide it

---

docs/resources/equinix_metal_device.md
equinix/resource_metal_device.go
equinix/resource_metal_device_acc_test.go

Our documentation incorrectly stated that the IDs in `user_ssh_key_ids` for an `equinix_metal_device` were the IDs of the SSH keys that will be supported on the device; in reality they are the IDs of the _users_ whose SSH keys will be supported.
In addition to the documentation, our tests were incorrectly attempting to pass an SSH key ID as a user ID, resulting in test failures due to errors from the API.

docs: update docs to clarify that the IDs in user_ssh_key_ids are user IDs

---

equinix/data_source_metal_spot_market_request.go
equinix/data_source_metal_spot_market_request_acc_test.go
equinix/resource_metal_spot_market_request.go

The spot market request resource sometimes fails tests because the `facilities` come back from the API in a different order than they appear in the terraform state.  This updates the resource to sort old and new facilities before comparing them so that we only trigger changes when absolutely necessary.
In addition, this sorts the facilities attribute in the spot market request data source to protect against potential reordering there; if the `facilities` come back in a different order from one terraform run to the next, it should not impact resources that reference the data source.

fix: suppress spot market diff when order of facilities changes

---

equinix/resource_metal_spot_market_request_acc_test.go

The spot market resource tests use a data source to determine the spot market price, and then attempt to create a spot market request with a bid price that is 20% higher than the spot market price.
This introduces brittleness to our tests because the bid price may be higher than the maximum allowed bid price.  This change uses the spot market price as the max bid price, rather than setting a higher bid, in an attempt to reduce the chance of test failure due to a disallowed bid price.

ci: use spot market price as max bid in tests

---

equinix/data_source_network_device.go

A patch for fixing issues when customers try to fetch redundant devices details in the data source.

NFV-25324: add schema for cloudInitFileId in secondary device data source

---

equinix/resource_metal_connection.go
equinix/resource_metal_connection_acc_test.go

fixes #276 
This PR makes speed param optional for shared z_connection.
I added test that creates the connection and checks that it's 10Gbps by default.

Make speed optional for shared z_side connection, add test

---

equinix/fabric_port_read_schema.go
equinix/resource_fabric_port.go
go.mod
go.sum

The Fabric V4 API Spec was updated in version 4.4 for the /fabric/v4/ports endpoint to return the redundancy.group property as a string instead of an integer. Only recently that change was actually implemented in the backend API and is causing a data source error in the Equinix Terraform Provider for Port2Port Connections.
The Terraform Provider does type assertions on the underlying Data Response Schema during Serialization of Resources for a Hash. If the schema does not match the returned types from API it will cause the plugin to crash without a helpful error message.
This change introduces the following updates:
1. Fix the schema type for the Port API response to TypeString from TypeInt
2. Add a recovery defer method in the data source resource for Port Retrieval to allow the provider …

Fabric Port Data Source Bug Fix

---

docs/resources/equinix_metal_project.md
equinix/resource_metal_device_acc_test.go
equinix/resource_metal_project.go

At some point, the Metal API introduced validation that rejects project names longer than 80 characters.  This broke one of our device tests, which was using the public SSH key contents as the project suffix instead of a random number.
This updates the broken test to use a random number suffix for project names so that the test can pass again.  The project resource docs are also updated to mention the 80-character limit.

chore(ci): fix SSH key test and document project name max length

---

docs/resources/equinix_metal_spot_market_request.md
equinix/resource_metal_spot_market_request.go

Fixes #253 
This PR fixes typo in spot_market_request argument name, it was supposed to be "termination" but ended up being "termintation". I added a new arg with a correct name and made the old on deprecated. We can remove it later on.
Done according to
https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations#renaming-an-optional-attribute

Typo in spot_market_request argument name: termintation->termination

---

equinix/config.go
go.mod
go.sum

This adds a metal-go client to the terraform provider.  The metal-go client can be gradually adopted by Metal resources and data sources in this provider to enable the eventual deprecation of packngo.
An example of using this client to interact with the Metal API can be found in #291.

feat: introduce metal-go client

---

equinix/data_source_metal_device.go
equinix/helpers_device.go
equinix/helpers_device_test.go
equinix/provider.go
equinix/provider_test.go
equinix/resource_metal_device.go
equinix/resource_metal_device_acc_test.go
equinix/resource_network_bgp_test.go
go.mod

Provides support for timeouts in Create, Update and Delete for Metal Device as already mentioned in the documents
#357

Upgrade metal device resource and data source to use timeouts

---

.github/workflows/acctest.yml

We don't need to hammer the API with end-to-end tests when the repo gets a flurry of activity.  This adds a concurrency setting to our acceptance test workflow with a hard-coded string value so that only one run of the acceptance tests can execute at any time.
This also updates the acceptance test workflow to replace the `pull` trigger with a `pull_request_target` trigger.  We've been using this for `metal-cli` and it has been a good experience thus far.  The new trigger allows us to manually run end-to-end tests for PRs from forks in order to build confidence in code changes before they are merged.

ci: run acctest workflows 1 at a time and support external PRs

---

equinix/config.go

At some point I switched the metal-go client creation function to use `logging.NewSubsystemLoggingHTTPTransport` instead of the deprecated `logging.NewTransport` that is used elsewhere.
However, I missed that `logging.NewSubsystemLoggingHTTPTransport` requires creating a subsystem first; since I didn't create a new subsystem, the metal-go HTTP debug logs were silently dropped.
This reverts to the `logging.NewTransport` to fix logging and match how we set up other clients.  We can explicitly work on dropping use of the deprecated function at a later time.

fix: wire up metal-go for HTTP debug logging

---

.github/workflows/validate_pr.yml

Currently our release process is fairly manual:  someone with write access to this repo has to check out the latest from `main`, look at what has changed since the last release, decide on an appropriate new version number, create a git tag in the correct format (is it `x.y.z` or `vx.y.z`?), and push that tag back up to GitHub to trigger the release process.
By ensuring that our PR titles have Conventional Commit tags, we make it possible to automatically determine the next release version number, which means we can move to a push-button release process: click the release button, and the workflow does the rest.
This workflow has been in place for some time on `metal-go` and was recently adopted in `metal-java`; adopting it more broadly will make it easier for us to safely share the …

ci: add workflow to enforce Conventional Commit tags

---

.github/workflows/acctest.yml

When I updated the acceptance test workflow to allow them to run against external PRs (by using the `pull_request_target` trigger), I forgot to update the workflow to actually check out the PR.  The `pull_request_target` workflow runs in the context of the base branch, so if it isn't explicitly told to check out something else, it will check out and run the tests from `main` instead of from the PR.

chore(ci): check out PR code for acceptance testing

---

.github/workflows/acctest.yml

In an earlier PR, I missed that the acctest workflow checks out code _both_ in the build job and in the test job.  I updated the build job to check out PR code, but the test job was still checking out code from the base branch.

chore: check out PR/branch code every time in acctest workflow

---

equinix/data_source_metal_virtual_circuit.go
equinix/resource_metal_virtual_circuit.go
equinix/resource_metal_virtual_circuit_acc_test.go
equinix/resource_network_bgp_test.go

https://github.com/equinix/terraform-provider-equinix/issues/357

fix: Timeout for metal virtual circuits

---

equinix/data_source_metal_vrf.go
equinix/resource_metal_vrf.go
equinix/resource_network_bgp_test.go

As part of fixing the timeouts for metal resources to actually comply with what is documented, it was found out that we donot document any timeout support for metal VRF whereas in the code we do have support for timeouts.
Since it has never been working due to the below issue, also not documented, it'll be ideal to remove it directly considering a code smell
Relates to: #357

fix: Remove timeout for metal vrf

---

docs/resources/equinix_metal_port.md
equinix/data_source_metal_port.go
equinix/port_helpers.go
equinix/resource_metal_port.go
equinix/resource_metal_port_acc_test.go
go.mod
go.sum

- Adds support for timeout in Create, update and delete operation.
- Adds acceptance tests
Fixes #357

fix: Update CRUD for metal port to support timeouts

---

equinix/data_source_metal_device_bgp_neighbors.go
equinix/data_source_metal_device_bgp_neighbors_acc_test.go

This updates the device BGP neighbors data source to use `metal-go` instead of `packngo`.  There were no tests for the BGP neighbors data source, so those are added here as well.

refactor: use `metal-go` for the BGP neighbors data source

---

docs/data-sources/equinix_metal_device.md
docs/data-sources/equinix_metal_devices.md
equinix/data_source_metal_devices.go
equinix/data_source_metal_devices_acc_test.go
equinix/helpers_device.go
equinix/provider.go

This PR adds `metal_devices` datasource, which fetches lists of device, similarly to [metal_plans](https://github.com/equinix/terraform-provider-equinix/blob/main/equinix/data_source_metal_plans.go) ([doc](https://registry.terraform.io/providers/equinix/equinix/latest/docs/data-sources/equinix_metal_plans))
fixes #288 
The datasource is using metal-go.

feat: metal_devices datasource

---

.github/workflows/acctest.yml
equinix/resource_metal_device_acc_test.go

Occasionally, we see metro or facility selections change as a result of capacity changes on the Metal platform side; for example, step 1 of a test deploys to `da`, but when step 2 runs, there are no longer any available servers in `da`, so a different metro is selected and the test generates an unexpected plan.

chore: use terraform_data resource to stabilize test selections

---

docs/data-sources/equinix_metal_connection.md
docs/resources/equinix_metal_connection.md
equinix/data_source_metal_connection.go
equinix/resource_metal_connection.go
equinix/resource_metal_connection_acc_test.go

fixes #340 
note:
- contact_email should be updatable but packngo does not offer the update field. Defining the field as ForceNew until this resource is rewritten with metal-go #402 
- e2e between the zside and shared test, we should have coverage that contact_email is optional and will be read back in as computed or as given. We are not adding a test that requires a project api key to trigger the backend *required* behavior.

feat: add contact_email to equinix_metal_connection datasource and resource

---

docs/resources/equinix_metal_connection.md

follow up to [#412 ](https://github.com/equinix/terraform-provider-equinix/pull/412#discussion_r1360880048)

docs: change metal_connection contact_email to not read as required

---

equinix/data_source_metal_ip_block_ranges_acc_test.go
equinix/resource_metal_bgp_setup_acc_test.go
equinix/resource_metal_device_acc_test.go
equinix/resource_metal_ip_attachment_acc_test.go
equinix/resource_metal_project_ssh_key_acc_test.go

We still had some Metal test failures due to changes in the `facilities` list for a selected plan.  In these cases, the tests were directly referencing the full `facilities` list rather than the single, cached, `facility` value.
This updates the tests to also cache the `facilities` list in an attempt to further reduce flakiness.  In addition, some tests that were using `facilities` have been updated to use `metro` instead, since none of the functionality under test was reliant on using `facilities`.

chore(ci): avoid test changes due to plan facilities

---

equinix/fabric_service_profile_read_schema.go
equinix/fabric_service_profile_search_schema.go
equinix/resource_fabric_service_profile.go

* Fabric 4.10 added viewPoint query parameter to serviceProfilesSearch Endpoint
* Fabric-Go SDK upgrade to v0.7.0 included the update to the method
* Terraform data source updated to reflect the changes in Fabric OAS 4.10
Testing with the cloudRouter2azure/two-connections E2E example:
TF_LOG Output:
Value not in main.tf:
```
---[ REQUEST ]---------------------------------------
POST /fabric/v4/serviceProfiles/search HTTP/1.1
Host: uatapi.equinix.com
User-Agent: equinix/fabric-go
Content-Length: 79
Accept: application/json
Authorization: Bearer 132E2S7hPtnrsk1GswoyDNoffwkK
Content-Type: application/json
X-Correlation-Id: 2@884TGRom#Fs#Ike9&35xDdO
X-Source: API
Accept-Encoding: gzip
{
"filter": {
"property": "/name",
"operator": "=",
"values": [
"Azure ExpressRoute"
]
}
}
```
Value set to …

feat: Add viewPoint parameter to Service Profiles Data Resource

---

equinix/fabric_cloud_router_schema.go
equinix/resource_fabric_cloud_router.go

- fix #428
- Add `MaxItems:1` for `project` argument. Although this is generally not a problem in terraform, [it does affect the way the Pulumi bridged plugin is generated](https://github.com/equinix/pulumi-equinix/issues/28). All fields of the type `set` without a `MaxItems` or `MaxItems` different to 1 are generated with a plural noun: `project` --> `projects`

fix: `equinix_fabric_cloud_router` ignore empty order block and set max 1 for project block

---

equinix/config.go

When the metal-go client was introduced to enable packngo deprecation, it was wired up directly to the `METAL_AUTH_TOKEN` environment variable for auth.  This breaks auth when a customer is using the `auth_token` provider configuration.
This updates the metal-go client initialization so that the client will work with both the `auth_token` setting and the `METAL_AUTH_TOKEN` env var.

fix: read metal-go client's auth token from config, not env

---

equinix/config.go

The code that injects terraform module information into the User-Agent string for the metal-go client was mis-wired; it was using the packngo User-Agent as a base instead of the metal-go User-Agent.  This change will correct the User-Agent so that requests made with metal-go will not appear to come from packngo.

fix: use the correct base User-Agent for metal-go requests

---

equinix/fabric_cloud_router_read_schema.go
equinix/fabric_cloud_router_schema.go
equinix/fabric_mapping_helper.go
equinix/resource_fabric_cloud_router.go
equinix/resource_fabric_cloud_router_acc_test.go

fix #455 - assign missed values in setMap:
```
"equinix_asn":           fcr.EquinixAsn,
"bgp_ipv4_routes_count": fcr.BgpIpv4RoutesCount,
"bgp_ipv6_routes_count": fcr.BgpIpv6RoutesCount,
"connections_count":     fcr.ConnectionsCount,
"order":                 orderToTerra(fcr.Order),
```
fix #456 
Update `waitUntilCloudRouterIsProvisioned` with values included in https://app.swaggerhub.com/apis/equinix-api/fabric/4.10#/CloudRouterAccessPointState (LOCKED not included due to lack of information, I don't know the FCR life cycle

fix: equinix_fabric_cloud_router provisioning state and read schema

---

internal/config/config.go
internal/config/correlation_id.go

CorrelationId was moved to internal/config and accidental made public. This PR makes it private.

fix: make correrlationI() function private

---

equinix/fabric_connection_read_schema.go
equinix/fabric_connection_schema.go
equinix/fabric_mapping_helper.go
equinix/resource_fabric_connection.go

This PR includes fixes for two defects(CXF-[81949](https://equinixjira.atlassian.net/browse/CXF-81949) & [CXF-81844)](https://equinixjira.atlassian.net/browse/CXF-81844)
- fixed service token schema
- fixed accespoint.interface schema

fix: fixing schemas for Servicetoken and accesspoint.interface.

---

equinix/resource_fabric_cloud_router.go
equinix/resource_fabric_connection.go
equinix/resource_fabric_port.go
equinix/resource_fabric_routing_protocol.go
equinix/resource_fabric_service_profile.go
internal/errors/errors.go

* Add errors method to output err and network response body together
* Update equinix_fabric_connection resource to include the errors method in response to errors on network requests
Part of https://github.com/equinix/terraform-provider-equinix/issues/124
Before:
```
equinix_fabric_connection.aws-qinq: Creating...
╷
│ Error: 400 Bad Request
│ 
│   with equinix_fabric_connection.aws-qinq,
│   on main.tf line 20, in resource "equinix_fabric_connection" "aws-qinq":
│   20: resource  "equinix_fabric_connection" "aws-qinq"{
```
After:
```
equinix_fabric_connection.aws-qinq: Creating...
╷
│ Error: 400 Bad Request; Code: EQ-3142501; Message: Invalid argument value passed; Details: Invalid notification emails; AdditionalInfo: [{Property: /notifications/emails, Reason: Not Provided}]
│ 
│   with …
```

fix: Add network body response in terraform errors for equinix_fabric_connection resource

---

equinix/fabric_connection_read_schema.go
equinix/fabric_connection_schema.go

This fix Includes:
- Added EVPLAN_VC,EPLAN_VC to fabric connection schema 
- Marked project_id as an optional parameter

fix: fixing fabric connection schema for port 2 network connection

---

equinix/provider_test.go
equinix/resource_ecx_l2_connection_acc_test.go
equinix/resource_ecx_l2_connection_test.go
equinix/resource_ecx_l2_serviceprofile_acc_test.go
equinix/resource_network_acl_template_acc_test.go
equinix/resource_network_bgp_acc_test.go
equinix/resource_network_device_acc_test.go
equinix/resource_network_device_link_acc_test.go
equinix/resource_network_file_acc_test.go
equinix/resource_network_ssh_key_acc_test.go

Some of the Network Edge tests were using `randInt` and `randString` to generate random integers and strings.  The only thing each function does is call an upstream function; this replaces all calls to those functions with direct calls to the upstream (which matches what we do in other tests) and removes the unnecessary wrappers.

refactor: remove unnecessary wrappers for getting a random string or int

---

equinix/data_source_metal_spot_market_request.go
equinix/provider.go

There was a private variable for default timeouts defined in `provider.go`, but it was only referenced in the spot market request data source.  Other resources and data sources define their default timeouts inline; this does the same for the spot market request data source so that it will be easier to move that data source to a different package than the one that `provider.go` is in.

refactor: move spot market timeouts out of provider.go

---

docs/data-sources/equinix_network_device.md
docs/resources/equinix_network_device.md
equinix/data_source_network_device.go
equinix/resource_network_device.go
equinix/resource_network_device_test.go
go.mod
go.sum

In Dec release, we added the "core" field to the [Update Virtual Device](https://developer.equinix.com/dev-docs/ne/api-reference/virtual-devices#update-virtual-device) API to allow users to resize their devices. After device is provisioned, the customer can send a PATCH request to upgrade its core number. The device will be marked as "RESOURCE_UPGRADE_IN_PROGRESS" and once the upgrade is done, the device status will be provisioned again.
More details could be found in our API documentation.
reference: https://developer.equinix.com/docs?page=/dev-docs/ne/overview
product reference: https://docs.equinix.com/en-us/Content/Interconnection/NE/user-guide/NE-VNF-resize.htm#UpgradeResourceSizeforClusterDeviceDeployment

feat: add VM resizing for device resource core upgrade and new device status for device data source

---

equinix/data_source_metal_device.go
equinix/data_source_metal_port.go
equinix/data_source_metal_spot_market_request.go
equinix/data_source_metal_virtual_circuit.go
equinix/data_source_metal_vrf.go
equinix/provider.go
equinix/resource_metal_device.go
equinix/resource_metal_port.go
equinix/resource_metal_reserved_ip_block.go
equinix/resource_metal_spot_market_request.go
equinix/resource_metal_virtual_circuit.go
equinix/resource_metal_vrf.go

While fixing timeout support in some of our resources, we introduced a private `diagnosticsWrapper` function to act as a shim between the context-aware resource lifecycle hooks and our pre-existing, non-context-aware resource lifecycle functions.  This shim was useful for gradual migration, but now it adds an unnecessary dependency between certain resources/datasources and the code in `provider.go`.
This removes the `diagnosticsWrapper` in favor of updating the resource lifecycle functions directly so that they have the correct function signature.  This work uncovered some places where we were needlessly calling `equinix_errors.FriendlyError`, so those are cleaned up here as well.

refactor: remove diagnostics wrapper

---

equinix/data_source_ecx_l2_sellerprofiles.go
equinix/data_source_network_account.go
equinix/data_source_network_device_type.go
equinix/provider.go
equinix/resource_ecx_l2_connection.go
equinix/resource_ecx_l2_serviceprofile.go
equinix/resource_network_acl_template.go
equinix/resource_network_device.go
equinix/resource_network_device_link.go
equinix/resource_network_file.go
internal/validation/strings.go

This moves some custom string validation functions out of `provider.go` and into the `validation` package so that resource & data source code is not tied so tightly to `provider.go`.

refactor: move validators out of provider.go

---

equinix/provider.go
equinix/resource_metal_port_vlan_attachment.go
internal/mutexkv/mutexkv.go

Moving mutexkv out of provider.go makes it easier to restructure our code.

refactor: move mutexkv to its own package

---

.github/ISSUE_TEMPLATE/config.yml

Update the community link in the GitHub Issue template so that it hits a Community landing page with a prominant button for starting new conversations. The previous link was to a listing page that did not offer a way to contribute until after login.
Instead of https://community.equinix.com/t5/forums/filteredbylabelpage/board-id/OR/label-name/Developer, go to https://community.equinix.com/developers

docs: update community link in issue template

---

equinix/provider.go
equinix/provider_test.go
equinix/resource_ecx_l2_connection.go
equinix/resource_ecx_l2_serviceprofile.go
equinix/resource_fabric_cloud_router.go
equinix/resource_fabric_connection.go
equinix/resource_fabric_routing_protocol.go
equinix/resource_network_device_link.go
internal/errors/errors.go
internal/errors/errors_test.go

This moves some private error-related functions out of `provider.go` into a separate package so that resources and data sources aren't unnecessarily tied to the provider code file.

refactor: move error functions out of package.go

---

equinix/data_source_ecx_l2_sellerprofiles.go
equinix/data_source_network_device_software.go
equinix/data_source_network_device_type.go
equinix/data_source_network_platform.go
equinix/fabric_mapping_helper.go
equinix/fabric_mapping_service_profile_helper.go
equinix/provider.go
equinix/resource_ecx_l2_connection.go
equinix/resource_ecx_l2_connection_test.go
equinix/resource_ecx_l2_serviceprofile.go
equinix/resource_ecx_l2_serviceprofile_test.go
equinix/resource_fabric_service_profile.go
equinix/resource_metal_vrf.go
equinix/resource_network_acl_template.go
equinix/resource_network_acl_template_test.go
equinix/resource_network_device.go
equinix/resource_network_device_test.go
equinix/resource_network_ssh_user.go
equinix/resource_network_ssh_user_test.go
internal/converters/converters.go

This moves some type conversion utility functions out of `provider.go` into the existing `converters` package so that they can be safely used by multiple resources and data sources without forcing those resources and data sources to be in the same package as the provider definition.

refactor: move converters out of provider.go

---

equinix/resource_metal_organization_acc_test.go

The terraform acceptance test for `metal_organization` creates an organization and then very quickly updates it.  The update step started failing at some point mid-2023 and was briefly fixed, but it has been failing consistently for quite a while now.
There is some background processing that happens when an organization is created, and the API will throw an error if the organization is updated before that background processing is finished.  This adds a delay between the create and update calls for an organization so that the affected test can pass.
Fixes #463.

chore: stabilize Metal organization test

---

internal/converters/converters.go

Fix #515.
The `TestAccMetalVRF_withIPRanges` started failing recently with an error that `ip_ranges` cannot be null.  It appears this test failure was caused by #509, which consolidated the [`expandListToStringList`](https://github.com/equinix/terraform-provider-equinix/pull/509/files#diff-17a1d27f648a15532c90c0ed8e7b143adde23b59dec5bbe4222db41a0a94ea0aL225-L232) and `IfArrToStringArr` functions.
This updates the `IfArrToStringArr` converter to match the old `expandListToStringList` implementation, which fixes the failing test.

fix: send an empty array for IP ranges instead of null

---

equinix/resource_fabric_connection.go

Added string(v4.PROVISIONING_ProviderStatus) to pending block for AWS connections

fix: fixing WaitForConnectionProviderStatus function for AWS connections

---

docs/resources/equinix_metal_device.md
equinix/helpers_device.go
equinix/helpers_device_test.go
equinix/resource_metal_device.go
equinix/resource_metal_device_acc_test.go
internal/errors/errors.go

We previously migrated the Equinix Metal device data source and the read pathways for the resource from `packngo` to `metal-go` (and then to `equinix-sdk-go`).  This finishes the migration of the device resource by replacing `packngo` with `equinix-sdk-go` in the create, update, and delete pathways for that resource.

refactor: finish moving device resource off of packngo

---

equinix/resource_fabric_cloud_router.go
equinix/resource_fabric_routing_protocol.go
internal/datalist/schema.go

Previous step to migrate testing functionality from github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource to github.com/hashicorp/terraform-plugin-testing/v2/helper/resource required to add e2e tests to migrate from SDKv2 to Framework https://github.com/equinix/terraform-provider-equinix/pull/406#issuecomment-1897294576
Almost all resource.StateChangeConf references had already been previously migrated to retry.StateChangeConf

refactor: migrate to plugin sdkv2 helper/id and helper/retry packages

---

equinix/data_source_fabric_port_acc_test.go

#526 adopted the terraform-plugin-testing module, but #520 introduced a new test that had a reference to the old terraform-plugin-sdk version of that module.  Since we don't have a requirement in place for PRs to be up-to-date before merging, #526 got merged without being updated to also fix the new test from #520, and as a result the `Go test` workflow started failing.  This updates the new test to match the others.

chore: fix test that is failing due to unrebased PR merges

---

equinix/data_source_metal_project.go
equinix/resource_metal_project.go
equinix/resource_metal_project_acc_test.go

This updates the Equinix Metal project resource and data source from the deprecated `packngo` SDK to `equinix-sdk-go`.
In order to change which SDK is used by the project resource, I also needed to [rewrite some tests so that they use a mock API instead of a mock SDK](https://github.com/equinix/terraform-provider-equinix/pull/517/commits/dc88ae02038b244180167340dfdbc2c79d8a8728).
Relates to #402

refactor: migrate project resource & data source to equinix-sdk-go

---

equinix/provider.go
equinix/provider_test.go
equinix/resource_ecx_l2_connection.go
equinix/resource_metal_organization.go
equinix/resource_network_device.go
equinix/resource_network_device_link.go
internal/schema/resourcedata.go
internal/schema/resourcedata_test.go
internal/schema/set_map.go

This moves some functions and related tests for detecting changes to resource data out of `provider.go` into its own package so that it's easier to isolate the SDK provider into its own package.  This was broken out of #518

refactor: move resource data change detectors to separate package

---

equinix/data_source_metal_device.go
equinix/data_source_metal_port.go
equinix/provider.go
equinix/resource_metal_device.go
equinix/resource_metal_device_network_type.go
internal/network/types.go

This moves some variables for Equinix Metal network types into its own package.  Removing this from provider.go will make it easer to move the existing SDK provider definition into a separate package from the provider resources & data sources.  This is broken out of

refactor: move network type declarations out of provider.go

---

docs/resources/equinix_fabric_cloud_router.md

The resource documentation should link to the product documentation. API documentation helps explain how the Terraform attributes map to the API, but it doesn't help a user understand what the underlying service is or why and where it should be used.

docs: link to product documentation for Equinix Fabric Cloud Router

---

equinix/resource_network_device.go

Add the missing core count device update back
The core count field was introduced in the following PR: https://github.com/equinix/terraform-provider-equinix/pull/492
Then it was deleted from this PR: https://github.com/equinix/terraform-provider-equinix/pull/509

fix: add the missing core count device update back

---

CODEOWNERS

Adds a codeowners using existing reviewer patterns.
The OWNERS file was a loosely tied benefit of:
https://github.com/equinix/terraform-provider-equinix/pull/142#issue-1237879622

chore: Add CODEOWNERS mapped by filenames

---

CODEOWNERS

One of the path mappings specified for the Network Edge (NE) team was `*equinix_network*` which didn't match any files.  This replaces that line with 2 lines to match NE resources and data sources.  We could use `*network*`, but that would catch `resource_metal_device_network_type.go`.
This also updates the default owners for code in this repo to DevRel Engineering, since we should be responsible for any code in this repo that is not specific to a particular service.

chore: fix NE path mappings and default owners in CODEOWNERS

---

.github/workflows/fabric_acctest.yml
equinix/resource_fabric_cloud_router_acc_test.go
equinix/resource_fabric_connection_acc_test.go

* Upload coverage artifacts in html format to see Go coverage details for each run
* Add empty test sweepers for Fabric to avoid failing jobs on sweepers that aren't related to Fabric tests

test: Update Fabric GHA workflow

---

.github/workflows/fabric_acctest.yml
equinix/data_source_fabric_connection_acc_test.go
equinix/data_source_fabric_port_acc_test.go
equinix/resource_fabric_connection.go
equinix/resource_fabric_connection_acc_test.go

* Added acceptance tests for fabric connection resource and data_source
* Updated attribute checks for fabric port acceptance tests
* Updated GHA to leverage ENV variables for newly added secrets for dedicated port data and connection test data

test: add acceptance tests for fabric connection resource/data_source and update port data_source tests

---

.github/workflows/acctest.yml
.github/workflows/fabric_acctest.yml

Relates to #542 
We've seen an increase in `text file busy` failures during test runs on some PRs.  After searching for that error message in GitHub issues for other providers, I landed on https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests#github-actions-workflow, which recommends using [the hashicorp/setup-terraform action](https://github.com/hashicorp/setup-terraform) in GitHub Actions workflows.
This updates our acceptance test workflows to use the setup action to install terraform, in the hopes that this reduces or eliminates the `text file busy` errors.

chore: update GHA workflows to use hashicorp/setup-terraform action

---

equinix/provider.go
equinix/resource_metal_virtual_circuit_acc_test.go
go.mod
go.sum
internal/resources/metal/project_ssh_key/datasource_test.go
internal/resources/metal/vrf/datasource.go
internal/resources/metal/vrf/datasource_test.go
internal/resources/metal/vrf/resource.go
internal/resources/metal/vrf/resource_test.go

This updates the Equinix Metal project resource and data source from the deprecated packngo SDK to equinix-sdk-go and moves them into separate package required for supporting plugin framework
Relates to https://github.com/equinix/terraform-provider-equinix/issues/402

refactor: Migrate VRF to equinix-sdk-go and move into separate package

---

internal/resources/metal/project/datasource.go
internal/resources/metal/project/datasource_test.go
internal/resources/metal/project/resource.go

The metal_project data source was attempting to read the organization ID for the specified project by looking directly at the `organization.id` field.  That field is only present on a project when the API request has `organization` in the `include` parameter.  Rather than include organization details and make the data source slower, this replicates the logic from the metal_project resource, which uses the organization's `href` field to get the organization ID.
While I was in this area of the code I also removed some debugging print statements that were merged unintentionally.

fix: correctly set organization_id in metal_project data source

---

equinix/resource_fabric_connection.go
equinix/resource_fabric_routing_protocol_acc_test.go

* Added acceptance test for routing protocol resource
* Data source tests for routing protocol resource included in resource file because of test setup
* Test setup creates an FCR, and a Connection on that FCR
* Config applies the Direct and BGP routing protocols to the created FCR connection
* Data_Source config retrieves the RPs created in the config
* Test assertions are performed on both the resource and data sources in the same test.
* Go test timeout must be >15m for it to work successfully

test: equinix_fabric_routing_protocol resource and data source

---

internal/config/config.go

A recent change to differentiate terraform-plugin-sdk traffic from terraform-plugin-framework traffic used the wrong Go module path for the SDK.  This fixes it so we can accurately track plugin-sdk version usage.

chore: fix module path used to determine terraform plugin SDK version

---

equinix/data_source_metal_devices.go
equinix/data_source_metal_plans.go
equinix/helpers_device.go
equinix/resource_metal_device.go
internal/datalist/schema.go
internal/resources/metal/project_ssh_key/datasource.go
internal/resources/metal/project_ssh_key/resource.go
internal/resources/metal/ssh_key/resource.go

We recently introduced equinix-sdk-go as a context-aware replacement SDK for packngo and _also_ migrated some resources and datasources to use context-aware CRUD lifecycle methods.  In those parallel changes we missed some opportunities to pass the terraform provider context into the SDK.
This updates the provider to replace all non-testing usage of `context.TODO()` and  `context.Background()` with references to the pre-existing terraform provider context.
Relates to #539

fix: maintain provider context in resources and datasources

---

.github/workflows/test.yml

I'm pretty sure we were capturing this previously because all tests (unit and integration) were running in the same workflow.  In any case, this captures the unit test coverage because it's at least as useful to track as the integration test coverage.
From what I can see in CodeCov docs, the unit and integration reports we upload for a particular commit will be merged automatically into one report, so we'll get a better picture of how well our code is covered.
This also updates the unit test workflow to trigger on every push to main; since these tests are lightweight and siolated, it's safe to run them frequently.  And it ensures that our test status badge in the README stays up-to-date!

chore: capture test coverage for unit tests

---

equinix/resource_metal_virtual_circuit_acc_test.go

The sweeper step of our end-to-end test workflow sometimes fails because it finds & attempts to delete virtual circuits that belong to shared interconnections.  The API blocks deletion of these circuits because they are API-managed, not user-managed, and can only be deleted by deleting the interconnection itself.  This adds a check to the virtual circuit sweeper so that the sweeper will ignore virtual circuits that belong to shared interconnections.

chore(ci): skip shared connections when sweeping virtual circuits

---

equinix/data_source_metal_device_acc_test.go
equinix/data_source_metal_device_bgp_neighbors_acc_test.go
equinix/data_source_metal_devices_acc_test.go
equinix/data_source_metal_facility_acc_test.go
equinix/data_source_metal_ip_block_ranges_acc_test.go
equinix/data_source_metal_metro_acc_test.go
equinix/data_source_metal_operating_system_acc_test.go
equinix/data_source_metal_organization_acc_test.go
equinix/data_source_metal_plans_acc_test.go
equinix/data_source_metal_port_acc_test.go
equinix/data_source_metal_precreated_ip_block_acc_test.go
equinix/data_source_metal_reserved_ip_block_acc_test.go
equinix/data_source_metal_spot_market_price_acc_test.go
equinix/data_source_metal_spot_market_request_acc_test.go
equinix/data_source_metal_vlan_acc_test.go
equinix/resource_metal_bgp_setup_acc_test.go
equinix/resource_metal_device_acc_test.go
equinix/resource_metal_ip_attachment_acc_test.go
equinix/resource_metal_organization_acc_test.go
equinix/resource_metal_organization_member_acc_test.go
equinix/resource_metal_port_vlan_attachment_acc_test.go
equinix/resource_metal_project_api_key_acc_test.go
equinix/resource_metal_vlan_acc_test.go

Every time we convert a resource from SDKv2 to framework, we end up needing to touch acceptance tests for unrelated resources so that those tests are using a provider that is aware of the moved resource.
Rather than making these changes piece-by-piece, this updates every Metal acceptance test so that they will be able to find a resource no matter which provider it is currently implemented in.

chore: update provider reference in all Metal acceptance tests

---

equinix/provider_test.go
equinix/resource_metal_device_acc_test.go
equinix/resource_metal_port_acc_test.go
equinix/resource_metal_reserved_ip_block_acc_test.go
equinix/resource_metal_spot_market_request_acc_test.go
internal/acceptance/acceptance.go
internal/resources/metal/project/datasource_test.go
internal/resources/metal/project/resource_test.go
internal/resources/metal/vrf/resource_test.go

A previous PR (#586) updated "all" Metal resource & datasource acceptance tests to use ProtoV5ProviderFactories instead of Provider so that we don't need to update unrelated tests whenever we migrate a resource from the SDK provider to the framework provider.
That PR missed a couple resources that are already in the `internal/` directory but aren't migrated to framework yet; this one updates the tests that were missed.

chore(ci): update test provider wiring for missed acceptance tests

---

internal/resources/metal/device/sweeper.go
internal/resources/metal/project/sweeper.go

This uses `go-multierror` to enable the project and device sweepers to continue to delete projects and devices even if one deletion fails.  Previously, the device and project sweepers would bail out after the first failed deletion, resulting in a number of unnecessary dangling resources.

chore(ci): delay sweep failure for more extensive cleanup

---

internal/acceptance/acceptance.go
internal/acceptance/context.go
internal/resources/metal/connection/datasource_test.go
internal/resources/metal/connection/resource_test.go
internal/resources/metal/gateway/resource_test.go
internal/resources/metal/project_ssh_key/datasource_test.go
internal/resources/metal/project_ssh_key/resource_test.go
internal/resources/metal/ssh_key/resource_test.go

when we define the ProviderFactories at TestStep level instead of TestCase and we run that single test it fails in CheckDestroy function because the client Meta() interface is nil. This PR adds a precheck to make sure the provider is always configured.

test: configure provider for upgradefromversion tests

---

docs/resources/equinix_metal_connection.md
internal/resources/metal/connection/datasource_test.go
internal/resources/metal/connection/resource.go
internal/resources/metal/connection/resource_schema.go
internal/resources/metal/connection/resource_test.go
internal/resources/metal/connection/speed.go

The Metal API was recently updated to change the behavior of shared interconnections as follows:
- VLANs must be specified at creation for shared connections
- VLANs cannot be updated for shared connections
This updates the connection resource to align with the new API behavior so that users can catch configuration errors earlier.
Note this rolls back #273, which was written to address #222.
This also includes a fix for #595

fix: vlans is now required in the Metal API for shared connections

---

docs/data-sources/equinix_metal_connection.md
docs/resources/equinix_metal_connection.md
internal/resources/metal/connection/datasource_schema.go
internal/resources/metal/connection/datasource_test.go
internal/resources/metal/connection/resource_schema.go
internal/resources/metal/connection/speed.go
internal/resources/metal/connection/speed_test.go

Previously, we maintained a list of valid connection speed values in the terraform provider in order to steer users towards selecting a valid connection speed.  As shown by #595, validating values in the provider has the potential to break when the list of connection speed values supported by the API changes.
This updates the code that converts speed values between integer and string representations (i.e., the code that knows that `"50Mbps"` is the same as `500000000`) to convert (roughly) arbitrary values.  This means that new values are immediately "supported" by the provider, but it also means that invalid values will not be flagged until apply.
The test change in this PR is sufficient to resolve the issue introduced by merging #605 without any other change to provider behavior.
Closes …

feat: push connection speed validation down to the API

---

internal/resources/metal/connection/sweeper.go
internal/resources/metal/virtual_circuit/sweeper.go
internal/resources/metal/vlan/sweeper.go
internal/sweep/sweep_test.go

The sweep task fails occasionally in CI because it attempts to delete VLANs that are attached to virtual circuits that belong to shared connections.  Virtual circuits on shared connections are API-managed and can only be deleted by deleting the shared connection, but we did not have a sweeper to clean up dangling shared connections after tests.
This adds a sweeper to clean up shared connections.  New shared connection types were recently added in the API, so the sweeper checks that a connection is not "dedicated" rather than checking that it is "shared."  A similar update was made to the virtual circuit sweeper.  The VLAN sweeper has been updated to declare the new connection sweeper as a dependency to ensure that shared connections have been cleaned up before we try to clean up VLANs.

chore(ci): sweep shared connections

---

equinix/data_source_fabric_cloud_router_acc_test.go
equinix/resource_fabric_cloud_router.go
equinix/resource_fabric_cloud_router_acc_test.go
equinix/resource_fabric_connection.go
equinix/resource_fabric_connection_acc_test.go
equinix/resource_fabric_network.go
equinix/resource_fabric_network_acc_test.go
equinix/resource_fabric_routing_protocol.go
equinix/resource_fabric_routing_protocol_acc_test.go
equinix/resource_fabric_service_profile.go
equinix/resource_fabric_service_profile_acc_test.go

* All fabric resource wait methods have new argument for timeout
* Using 30*time.Second to account for delay in wait methods
* Timeout is for entire CRUD method so we subtract times as we go from the start of the method
* Testing updated to account for changes
NOTE: We have errors running Fabric tests in parallel for now. Not sure of the issue, but this change has been testing manually locally with each test being run in an isolated manner. All tests are successful. Logs are too large to post.

fix: Use default timeouts for Fabric wait methods

---

internal/resources/metal/project/models.go
internal/resources/metal/project/resource_test.go

During the framework migration of the project resource, we missed that the framework-based resource doesn't correctly handle null values for the `md5` attribute in BGP config.
This updates the basic project BGP test to cover that aspect of the project resource and updates the project model to avoid setting the in-state md5 value to `""` when it should be `nil`.
Closes #630

fix: correctly handle null MD5 in project BGP settings

---

docs/data-sources/equinix_metal_gateway.md
docs/data-sources/equinix_metal_reserved_ip_block.md
docs/data-sources/equinix_metal_virtual_circuit.md
docs/data-sources/equinix_metal_vrf.md
docs/resources/equinix_metal_gateway.md
docs/resources/equinix_metal_reserved_ip_block.md
docs/resources/equinix_metal_virtual_circuit.md
docs/resources/equinix_metal_vrf.md

Replace this text:
> ~> VRF features are not generally available. The interfaces related to VRF resources may change ahead of general availability.
With this:
> See the [Virtual Routing and Forwarding documentation](https://deploy.equinix.com/developers/docs/metal/layer2-networking/vrf/) for product details and API reference material.

docs: remove disclaimers about VRF being beta

---

internal/resources/metal/vlan/models.go
internal/resources/metal/vlan/resource.go
internal/resources/metal/vlan/resource_test.go

When the equinix_metal_vlan resource was migrated (#578) from terraform-plugin-sdk/v2 (SDKv2) to terraform-plugin-framework (framework), some unintended behavior was introduced around the description and metro attributes.
For equinix_metal_vlan resources under SDKv2, description was an optional attribute and metro was case insensitive, but after migration from SDKv2 to framework, the description was set to `""` when the attribute was omitted, and metro was required to be lower-case to avoid terraform errors.
This updates the VLAN model parsing function so that:
- if there is already metro value configured in state and it is equal to the value received from the API or from the config, ignoring case, then the value that is already in state is used instead of the value from the API
- if …

fix: avoid inconsistent state errors for vlans

---

go.mod
go.sum

Follow-up to #606 
Closes #648

chore: run 'go mod tidy' to clean up dependencies

---

equinix/resource_fabric_connection.go

- Updated resourceFabricConnectionCreate method by passing additional_info parameters only when it's required

fix: Updating CreateConnection method for passing additional_info in Updating Create Connection method in Fabric connection Resource

---

equinix/resource_fabric_connection.go

- Added CONNECTIONSTATE_ACTIVE, CONNECTIONSTATE_PENDING to pending stage in  WaitUntilConnectionDeprovisioned method to resolve issue for Oracle Connection deletion process.

fix: Adding ACTIVE connection state to WaitUntilConnectionDeprovisioned method for pending stage

---

equinix/port_helpers.go
equinix/resource_metal_device.go
equinix/resource_metal_port.go
go.mod
go.sum
internal/resources/metal/device/sweeper.go

The slices package was promoted from `golang.org/x/exp` to the standard library in go1.22.  This upgrades go and replaces usage of the old exp slices package with the equivalent stdlib package.  This removes the need for #662

chore: build with go 1.22 and use slices from stdlib

---

docs/resources/equinix_fabric_connection.md

- Updated connection type in following examples in Fabric Connection Resources Doc:
- vd2azure connection
- vd2azure redundant connection

fix: Updating Virtual device to service profile connections type in fabric connection resource doc

---

go.mod
go.sum
renovate.json

We periodically have to manually run `go mod tidy` to clean up our dependencies because Renovate doesn't run that by default for its update PRs.  This runs one last manual tidy and updates the Renovate configuration to tell Renovate to clean up after itself from now on.
Reference: https://docs.renovatebot.com/configuration-options/#postupdateoptions

chore: tell renovate to run go mod tidy after updating

---

equinix/resource_fabric_connection.go

- Setting Redundancy group only when it's not empty

fix: Updating connectionRedundancyTerraformToGo fucntion

---

equinix/data_source_network_device.go
equinix/provider.go
equinix/resource_ecx_l2_connection.go
equinix/resource_network_device.go

Remove isStringInSlice in favor of slices.Contains.
Extracted from #622 
Related to #665

refactor: replace isStringInSlice with slices.Contains

---

CODEOWNERS

Capture Network Edge documentation file patterns in CODEOWNERS.
Also removes @t0mk from CODEOWNERS.

chore: capture Network Edge documentation in CODEOWNERS

---

equinix/resource_fabric_routing_protocol.go

fix: resource_fabric_routing_protocol.go added more compute fields to the file resource_fabric_routing_protocol.go since  Routing Protocol is updating when no Changes are made for Routing Protocol Modules while updating Connection_Name and Bandwidth.

fix: resource_fabric_routing_protocol.go

---

docs/data-sources/equinix_metal_virtual_circuit.md
docs/resources/equinix_metal_virtual_circuit.md
equinix/provider.go
equinix/resource_metal_virtual_circuit.go
equinix/resource_metal_virtual_circuit_acc_test.go
internal/resources/metal/virtual_circuit/datasource.go
internal/resources/metal/virtual_circuit/resource.go
internal/resources/metal/virtual_circuit/resource_test.go
internal/resources/metal/virtual_circuit/sweeper.go

This updates the `metal_virtual_circuit` resource and data source to use `equinix-sdk-go` instead of `packngo`.  As mentioned in #402, the `packngo` SDK has been deprecated, and moving to `equinix-sdk-go` makes it possible for these resources to gain new features in the future.
As an added bonus, the affected code has also been moved to `internal/resources/metal` to align with #106.

feat: convert virtual circuit resource & datasource to equinix-sdk-go

---

equinix/resource_network_bgp_acc_test.go
equinix/resource_network_device_acc_test.go

feat: Update Network Edge BGP Acceptance Tests to use fabric resources(fabric connection and service profile)

feat: Update Network Edge BGP Acceptance Tests to use fabric resources(fabric connection and service profile)

---

internal/resources/fabric/connection/models.go

This checks that the serviceTokenType is only set when it is not an empty String value.

fix: zSide.serviceToken.type. Unexpected value '' error message

---

internal/resources/metal/gateway/models.go
internal/resources/metal/gateway/resource_test.go

This PR fixes a bug when creating metal gateways associated with IPv6 reservations. Previously the provider would assume the gateway was tied to an IPv4 reservation, which would result in an error when the `calculateSubnetSize` function was called. 
To fix this, an additional check was added to the `calculateSubnetSize` function which ensures the address is actually `IPv4` before executing the private ipv4 subnet logic.
Additionally an acceptance test was added which creates a metal gateway associated with an IPv6 reservation and VRF.

fix: Fix provider crash when creating a metal gateway tied to an ipv6 reservation

---

internal/config/config.go
internal/resources/metal/organization/resource.go

This removes some unnecessary print statements for debugging the organization resource as well as the unused `DumpTransport` type.  The functionality of the `DumpTransport` type is already available by setting `TF_LOG=debug` and doesn't require a custom implementation.

chore: clean up debug code that is no longer needed

---

.github/workflows/release.yml
.goreleaser.yml
.releaserc.json
RELEASE.md

Currently, the release workflow requires someone to manually inspect the changes since the last release, decide on a good version number to use, create that tag locally, and push it to GitHub to trigger a release.
Instead, this follows the pattern established with our generated SDKs, which use Conventional Commits tags to automatically determine the next release version and construct the release notes for the GitHub release.
The updated push-button workflow creates the correct release automatically and then runs the pre-existing goreleaser action to attach the terraform provider builds to the existing GitHub release.

chore(ci): convert to a push-button release workflow

---

equinix/provider.go
equinix/provider_test.go
internal/comparisons/comparisons.go
internal/comparisons/comparisons_test.go

This PR moves the helper functions from provider.go to a new comparisons package. This package will be used by provider, tests, and resources. The refactoring will assist with splitting resources into resource specific packages. #106 
The previous helper functions have been deprecated and will be removed in a future commit.
Extracted from #622 (PR grew to large to maintain. Refactoring is not a priority and rebasing gets hard as the underlying code changes)
Related to #674
Related to #654

refactor: add comparisons pkg for reused helpers

---

.github/workflows/golangci-lint.yml
.golangci.yaml
GNUmakefile

This introduces linting in CI to help maintain code quality and identify issues that may not be caught by tests.  To avoid a big PR that resolves all existing linting issues, the CI workflow is configured to only look at files that are changed in a particular PR or commit; we'll need to keep an eye on this to make sure it's working as expected.  This will allow us to chip away at existing issues over time.  Eventually (ideally within a few months), the CI workflow should be updated to always lint the entire codebase.
This PR also introduces a `make lint` task for local execution, but this task lints the entire codebase and, for the time being, will catch some issues that are not flagged for a particular PR or commit in CI.

chore(ci): lint with golangci-lint

---

CODEOWNERS

#727 incorrectly required review from DevRel Engineering; all files in that PR were specific to Network Edge (NE).  This updates the CODEOWNERS mappings so that NE documentation templates are owned by the NE team.

chore: assign ownership of Network Edge (NE) templates to the NE team

---

.github/workflows/fabric_acctest.yml
internal/config/config.go
internal/resources/fabric/connection/resource_test.go
internal/resources/fabric/connection/sweeper.go
internal/sweep/sweep.go
internal/sweep/sweep_test.go

* Add test sweeper for fabric connections
* Modify internal/sweep package with constants, list var, and methods to support test sweeping for fabric
* Add config for fabric test client

test: Fabric Connections test sweeper

---

internal/config/config.go

Previously we validated that the user specified at least one kind of Equinix credential during provider startup.  This behavior is unusual among Terraform providers and its utility is debatable, because it does not and cannot protect against these situations:
- Invalid credentials were provided
- Credentials were omitted for a service that is used (e.g., a Metal auth token was specified, but a client ID and secret were needed for the resources in the user's configuration)
In addition to the above shortcomings, validating credentials in the Config type that is shared between SDKv2 and framework providers forces unnecessary changes to the SDKv2 provider if a new service is onboarded to the framework provider.
This removes the credential validation from the config object so that any and all …

feat: remove credential validation on provider startup

---

equinix/provider.go

The linter will complain if any changes are made in `equinix/provider.go` because we are using a deprecated stop context for coordinated shutdown across resources.  We have to continue using a stop context until all resources and data sources are updated to use context-aware CRUD functions.  This disables staticcheck for the relevant line of code and adds a comment explaining why linting was disabled in this case.

chore: allow continued use of stop context for now

---

README.md

The Metal acceptance test workflow was renamed.  This removes the broken badge rather than adding working badges for the Metal and Fabric acceptance test workflows because both of those are failing at the moment, and advertising that is probably counterproductive.
This also replaces the Metal Slack & Twitter badges with an Equinix Community badge, since the provider covers more than just Metal and Community is the place to go for cross-product discussion.

chore(docs): fix badges in readme

---

.golangci.yaml
GNUmakefile

By default, golangci-lint will only report a certain number of issues per linter and a certain number of the same issue per run.  That adds unnecessary turnaround time when fixing issues.
This PR updates our golangci-lint config file to tell the linter to report all errors.
The golangci-lint config structure has changed quite a bit since v1.56, so rather than fight their docs I'm also upgrading the linter to the latest.

chore(ci): tell golangci-lint to report all issues

---

equinix/data_source_metal_devices.go

The data source `metal_devices` fails to retrieve all hosts within a project. This PR uses `ExecuteWithPagination` to retrieve the full list of resources.

fix: use pagination for data source metal_devices

---

equinix/common_test.go
equinix/data_source_metal_device_bgp_neighbors_acc_test.go
equinix/provider.go
equinix/resource_metal_spot_market_request.go
internal/resources/metal/device/datasource.go
internal/resources/metal/device/datasource_test.go
internal/resources/metal/device/helpers.go
internal/resources/metal/device/helpers_test.go
internal/resources/metal/device/list_datasource.go
internal/resources/metal/device/list_datasource_test.go
internal/resources/metal/device/resource.go
internal/resources/metal/device/resource_test.go
internal/resources/metal/device/sweeper.go

This moves the device resource and data sources out of the `equinix` package and into an isolated directory & package to align with #106.

refactor: move device resource and datasource to separate package

---

internal/errors/errors.go
internal/resources/fabric/cloud_router/sweeper.go
internal/resources/fabric/connection/sweeper.go
internal/resources/fabric/route_filter/sweeper.go
internal/resources/metal/device/helpers.go
internal/resources/metal/device/helpers_test.go
internal/resources/metal/device/resource.go
internal/resources/metal/device/resource_test.go
internal/resources/metal/gateway/resource.go
internal/resources/metal/port/resource.go
internal/resources/metal/project/bgp_config.go
internal/resources/metal/project/resource.go
internal/resources/metal/project/resource_test.go
internal/resources/metal/project_ssh_key/datasource.go
internal/resources/metal/project_ssh_key/resource.go
internal/resources/metal/ssh_key/resource.go
internal/resources/metal/virtual_circuit/resource.go
internal/resources/metal/virtual_circuit/sweeper.go
internal/resources/metal/vrf/resource.go

This was broken out of #782 since it involves a widely-used helper function and will impact more than just the Metal VLAN resource.
Previously, the `IgnoreHttpResponseErrors` helper function accepted as arguments a number of other, existing helper functions that are meant to evaluate whether a particular API response has a certain HTTP status.  Here's [an example helper function for checking if the response is a 403](https://github.com/equinix/terraform-provider-equinix/blob/b1ed71b389705513308c1e47e7ac6ff0c46891cd/internal/errors/errors.go#L119-L130):
```go
func HttpForbidden(resp *http.Response, err error) bool {
if resp != nil && (resp.StatusCode != http.StatusForbidden) {
return false
}
switch err := err.(type) {
case *ErrorResponse, *packngo.ErrorResponse:
return IsForbidden(err)
} …
```

refactor: ignore HTTP response errors by status code

---

docs/resources/network_device.md
examples/resources/equinix_network_device/Aviatrix_Transit_Edge.tf
templates/resources/network_device.md.tmpl

feat: Update docs for New device type - "Aviatrix Transit Edge" under Aviatrix Vendor

feat: Update docs for New device type - "Aviatrix Transit Edge" under Aviatrix Vendor

---

internal/resources/metal/port/helpers.go
internal/resources/metal/port/resource_test.go

Some packngo usage was missed in #709.  This completely removes packngo from metal_port, as well as calls to `FriendlyError` because that function has no impact for non-packngo errors.

refactor: finish removing packngo from metal_port code

---

equinix/fabric_provider_maps.go
equinix/metal_provider_maps.go
equinix/network_edge_provider_maps.go
equinix/provider.go
internal/provider/provider.go
internal/provider/services/fabric.go
internal/provider/services/metal.go
internal/provider/services/network_edge.go

This refactors the SDKv2 and framework providers so that the data sources and resources for each Equinix service are defined in separate files.  This enables each team to add or remove their own data sources and resources without requiring review from DRE.

chore: allow teams to add/remove resources & data sources

---

.github/workflows/validate_pr.yml

To ensure that we continue to make progress on #106, this updates the `Validate PR` GitHub Actions Workflow to check if new Go files have been added to the `equinix/` directory.
The workflow only checks for [files with `"added"` status](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests-files) that are directly under the `equinix/` directory.  This leaves room for renaming/copying files and for adding new packages in `equinix/<subdirectory>/`.

chore: prevent new Go files from being added to equinix package

---

go.mod

Renovate seems to be tripping on the new Go version as part of upgrading Go dependencies.

chore: upgrade go to 1.23

---

docs/resources/fabric_service_token.md
examples/resources/equinix_fabric_service_token/zside_colo_service_token.tf
internal/resources/fabric/service_token/resource_test.go
templates/resources/fabric_service_token.md.tmpl

-Added Zside Port Service Token Resource Acc Tests
- Updated docs for Service Token Resource

feat: Adding Zside Port Service Token resource

---

equinix/resource_fabric_cloud_router.go

* Add support for updating cloud router notifications attribute
* Modify update requests method to allow all possible attribute changes in one update lifecycle
* Occurs through multiple API requests to the same endpoint allowing some to fail while still succeeding on the others
* Fix the update issue on package code; resolves https://github.com/equinix/terraform-provider-equinix/issues/829

fix: Fabric Cloud Router Update Method

---

docs/resources/fabric_service_token.md
examples/resources/equinix_fabric_service_token/aside_colo_service_token.tf
examples/resources/equinix_fabric_service_token/zside_colo_service_token.tf
examples/resources/equinix_fabric_service_token/zside_network_service_token.tf
internal/resources/fabric/service_token/models.go
internal/resources/fabric/service_token/resource.go
internal/resources/fabric/service_token/resource_schema.go
internal/resources/fabric/service_token/resource_test.go
templates/resources/fabric_service_token.md.tmpl

- Updated Service Token Resource Schema and Model
- Updated docs for Service Token to add zside Network based token

feat: Updating Service Token Resource for network based token

---

.github/workflows/release.yml
.goreleaser.yml
.releaserc.json

We have intermittently seen provider releases fail to show up in the Terraform registry.  When that happens we can usually redeliver the GitHub release webhook event and get the registry to find the new release.
While working on changes to the Equinix Python SDK, it occurred to me that the webhook issues we are seeing might be related to how we do automatic releases.  The semantic-release-action creates the GitHub release, and then the provider artifacts are built and uploaded by GoReleaser after the GitHub release has been created.  The webhook event is sent to the Terraform registry when the release is created, not after the artifacts are uploaded; it's possible that the registry attempts to load the release only to find that it does not include a provider, and that that is why our …

chore(ci): delay release publish until after artifacts are attached

---

README.md
docs/guides/migration_guide_equinix_metal.md
docs/guides/migration_guide_packet.md
templates/guides/migration_guide_equinix_metal.md
templates/guides/migration_guide_packet.md

This updates the docs to remove the incorrect mention of support for Terraform <1, which was dropped in v3 of this provider, as well as references to the migration tool, which has been unmaintained for some time, is no longer included in provider releases, and will be removed from this codebase entirely in the near future.

docs: remove/update incorrect provider documentation

---

.golangci.yaml

* Enable `revive` and `stylecheck` linters

chore: Enable revive and stylecheck in golangci linters

---

.github/workflows/golangci-lint.yml
GNUmakefile

Since we might periodically change linter configuration, as done in #849, we should keep the existing PR validation behavior that only lints the files that were changed in a particular PR.  This will allow us to continue to avoid unnecessarily large PRs to fix linting failures if and when the linter configuration changes.
If we're keeping the current, limited PR validation behavior, we should use the same behavior for the `make lint` task to that developers can easily identify the minimum necessary changes locally.  This updates the `make lint` task to only lint files that have been changed since `origin/main`, which should closely approximate the behavior of the PR validation workflow.

chore: update local lint task to only lint changed files

---

internal/resources/fabric/network/sweeper.go
internal/sweep/sweep_test.go

**Test Sweeper for Networks:** 
-Added test sweeper in`internal/resources/fabric/network/sweeper.go`
-Added `network.AddTestSweeper()` function call in `internal/sweep/sweep_test.go`
A screenshot of the sweeper test run:

feat: Create Test Sweeper for Networks

---

.golangci.yaml

HashiCorp examples encourage the use of underscores in names in Terraform provider tests.  To avoid unnecessary churn due to renaming things in test files, we disabled the relevant `revive` rule for tests, but it turns out there's a similar `stylecheck` rule that also needs to be skipped.  This PR disables that rule for test files.

chore: allow underscores in names in test files

---

internal/resources/fabric/stream_subscription/resource.go

* Pulling from `plan` for update method causes issues because it will use the results of computed values from state instead of just what is present from user input
* Use config instead of plan to just get user input

fix: Update method should pull from config instead of plan

---

docs/data-sources/fabric_network.md
docs/resources/fabric_network.md
internal/resources/fabric/network/resource_schema.go
internal/resources/fabric/network/resource_test.go

- Add `EVPTREE` and `EPTREE` Network Type in  `internal/resources/fabric/network/resource_schema.go`
- Generate docs (Updates `docs/data-sources/fabric_network.md` and `docs/resources/fabric_network.md`) 
- Tested network creation in `terraform-equinix-fabric` modules (network created successfully) 
- Add acceptance test - `TestAccFabricCreateEVPTREE_Network_PFCR` in `resource_test.go`

feat:  Addition of E-Tree Network Type

---

renovate.json

* Instead of manually updating commit digests as shown in #913 , this renovate extension should perform the same changes in a less copy-paste error prone manner

feat: Add extension to renovate to do gha action digest pinning

---

internal/sweep/services/fabric.go
internal/sweep/services/metal.go
internal/sweep/sweep_test.go

This replicates the approach taken for provider resource and data source registration in #797 and applies it to test sweeper registration so that service teams can add and remove test sweepers for their own resources as needed without waiting for review from a cross-cutting team.

chore: enable code review by service owners for test sweepers

---

docs/data-sources/metal_spot_market_request.md
docs/resources/metal_spot_market_request.md
equinix/data_source_metal_spot_market_request.go
equinix/resource_metal_spot_market_request.go
templates/data-sources/metal_spot_market_request.md.tmpl
templates/resources/metal_spot_market_request.md.tmpl

To declare deprecation for spot market, this is to mark the endpoint as deprecated.
No customers are using spot market currently and have been communicated of sunset.

chore: deprecate spot-market requests

---

docs/data-sources/fabric_stream_subscription.md
docs/data-sources/fabric_stream_subscriptions.md
docs/resources/fabric_stream_subscription.md
internal/resources/fabric/stream_subscription/datasources_schema.go
internal/resources/fabric/stream_subscription/models.go
internal/resources/fabric/stream_subscription/resource.go
internal/resources/fabric/stream_subscription/resource_schema.go

Add new field - `format` (this is only present in webhook and grafana stream subscriptions)

fix: Update terraform provider to add format field for grafana stream subscription
