equinix/terraform-provider-equinix

CHANGELOG.md, docs/resources/ecx_l2_connection.md, docs/resources/ecx_l2_connection_accepter.md, docs/resources/ecx_l2_serviceprofile.md, docs/resources/network_acl_template.md, docs/resources/network_bgp.md, docs/resources/network_device.md, docs/resources/network_device_link.md, docs/resources/network_ssh_key.md, docs/resources/network_ssh_user.md, equinix/resource_ecx_l2_connection.go, equinix/resource_ecx_l2_connection_accepter.go, equinix/resource_ecx_l2_connection_accepter_acc_test.go, equinix/resource_ecx_l2_serviceprofile.go, equinix/resource_ecx_l2_serviceprofile_acc_test.go, equinix/resource_network_acl_template.go, equinix/resource_network_acl_template_acc_test.go, equinix/resource_network_bgp.go, equinix/resource_network_bgp_acc_test.go, equinix/resource_network_device.go, equinix/resource_network_device_acc_test.go, equinix/resource_network_device_link.go, equinix/resource_network_device_link_acc_test.go, equinix/resource_network_ssh_key.go, equinix/resource_network_ssh_key_acc_test.go, equinix/resource_network_ssh_user.go
Fixes #49 
https://www.terraform.io/docs/extend/resources/import.html
=> implement the passthrough importer for all resources

CHANGELOG.md
Signed-off-by: Marques Johansson <mjohansson@equinix.com>
=> update CHANGELOG.md for 1.3.0

examples/connectivity/azure-connection/main.tf
=> Fix connectivity example to establish an azure connection

CHANGELOG.md
https://github.com/equinix/terraform-provider-equinix/pull/89/files?short_path=06572a9#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed
=> update changelog for 1.4.0

docs/index.md, docs/resources/equinix_ecx_l2_connection.md, docs/resources/equinix_metal_spot_market_request.md, docs/resources/equinix_network_device.md, docs/resources/equinix_network_device_link.md
Signed-off-by: Marques Johansson <mjohansson@equinix.com>
=> update documentation links for timeout parameters

CHANGELOG.md, docs/resources/equinix_ecx_l2_connection.md, docs/resources/equinix_metal_connection.md
Added description of service_token field and link to Equinix documentation
=> equinix_ecx_l2_connection.service_token field added in docs

docs/resources/equinix_network_device.md, equinix/resource_network_device.go, equinix/resource_network_device_acc_test.go, go.mod, go.sum
Cluster is introduced in device creation API. Some new device and device license pending states are introduced along with it.
Device provisioning time has been updated to 90 minutes considering the cluster scenarios.
Go module has been cleaned up by go mod tidy and ne-go has been upgraded to v1.4.0
reference: https://developer.equinix.com/docs/launch-cluster-device
This terraform availability is part of April release scope for NE.
=> NFV-18043: add cluster availability in device creation API

docs/resources/equinix_network_device.md, equinix/resource_network_device.go, equinix/resource_network_device_acc_test.go, go.mod, go.sum
The pr will allow the customer to add mgmt acl in the device creation flow. It will also allow them updating the mgmt acl for the device in place. 
This PR is dependent on ne-go changes 
https://github.com/equinix/ne-go/pull/12
=> NFV-18247: add mgmt acl in device creation and update flow

equinix/resource_metal_port_vlan_attachment_acc_test.go
Formerly: https://github.com/equinix/terraform-provider-metal/pull/66 created by @displague 
I transferred this PR as a draft, it seems it got stuck due to an unrelated error
@displague can you confirm this PR is ready to go?
=> specify test location dynamically in L2 VLAN attachment tests

CHANGELOG.md
Signed-off-by: Marques Johansson <mjohansson@equinix.com>
=> update CHANGELOG for 1.8.1

docs/resources/equinix_metal_connection.md, equinix/resource_metal_virtual_circuit.go
=> Update metal vc vlan

docs/guides/migration_guide_facilities_to_metros_devices.md
=> docs: Update facility migration guide with links to facility deprecation info

equinix/resource_metal_spot_market_request_acc_test.go, equinix/resource_metal_virtual_circuit.go
A previous fix (removing unnecessary `port` from the VC state
waiter in #332) uncovered a downstream API error in the virtual circuit
delete code when deleting a VRF virtual circuit.
When any virtual circuit is deleted, the terraform provider was
trying to disconnect the VLAN from the circuit. For the VRF virtual
circuit tests, this request was getting a 422 response from the
API with the message "Update params can't be blank". Running
locally, both the VRF and VLAN virtual circuit tests pass without
this explicit disconnect request.
=> fix: don't set empty vnid before deleting virtual circuit

.github/ISSUE_TEMPLATE/question.md, docs/guides/equinix_fabric_cloud_providers.md, docs/guides/migration_guide_equinix_metal.md, docs/resources/equinix_metal_device.md
fix: fix broken ipxe link in example
doc: Update links of master branch to be links to main branch
=> Master to main

go.mod, go.sum
ecx-go 2.3.1 fixes https://github.com/equinix/terraform-provider-equinix/issues/347
=> bump ecx-go version to latest

equinix/resource_metal_device_acc_test.go, go.mod, go.sum
- updates packngo to v0.30.0
- adds Rescue to packngo mock DeviceService interface
=> chore(deps): updates packngo to v0.30.0

docs/data-sources/equinix_network_device.md, docs/resources/equinix_network_device.md, equinix/data_source_network_device.go, equinix/resource_network_device.go, equinix/resource_network_device_acc_test.go, equinix/resource_network_device_test.go, go.mod, go.sum
In the August release, NE has introduced a new feature that enables customers to create devices with or without internet access. To accommodate this change, the Terraform code has been updated. Below is the reference for these changes.
Reference: https://developer.equinix.com/docs?page=/dev-docs/ne/overview
=> NFV-25337: Added attribute Connectivity to support device creation with no internet access

equinix/resource_metal_device_acc_test.go
We have a few tests for the device resource that cover scenarios that are impossible to reliably recreate in an end-to-end test.  These tests were originally based on a mock packngo client, but mocking the SDK hides issues that may come in due to SDK upgrades and requires changing tests when we switch to a different SDK.
This updates the device mock tests to use a mock API created with the built-in `httptest` module so that we can more easily validate that the tests continue to pass after upgrading or changing the SDK.
=> test: refactor device resource tests to mock API instead of SDK

equinix/fabric_connection_read_schema.go, equinix/fabric_connection_schema.go, equinix/fabric_mapping_helper.go, examples/fabric/v4/cloudRouterConnectivity/cloudRouter2wan/README.md, examples/fabric/v4/cloudRouterConnectivity/cloudRouter2wan/main.tf, examples/fabric/v4/cloudRouterConnectivity/cloudRouter2wan/terraform.tf, examples/fabric/v4/cloudRouterConnectivity/cloudRouter2wan/terraform.tfvar.example, examples/fabric/v4/cloudRouterConnectivity/cloudRouter2wan/variables.tf
- Adds support for a new connection type: FCR to IPWAN
- Includes changes to the connection schema to support the above type
- Incudes tests and terraform examples
=> feat: Adds Fabric cloud router to IPWAN network connection support

docs/data-sources/equinix_fabric_service_profiles.md
=> docs: Add view_point to service profile data source docs

docs/index.md
=> docs: update Client ID & Secret provider instruction link

docs/data-sources/equinix_fabric_connection.md, docs/resources/equinix_ecx_l2_connection.md, docs/resources/equinix_fabric_connection.md, equinix/fabric_connection_schema.go, equinix/fabric_mapping_helper.go, examples/fabric/v4/portConnectivity/ibm/ibm2/README.md, examples/fabric/v4/portConnectivity/ibm/ibm2/main.tf
Fixed resource_fabric_connection by adding Type and Interface parameters to access_point. 
Updated equinix_fabric_connection.md file
=> fix: Fixing VD to Azure connection resource

docs/data-sources/equinix_ecx_l2_sellerprofile.md, docs/data-sources/equinix_ecx_l2_sellerprofiles.md, docs/data-sources/equinix_ecx_port.md, docs/resources/equinix_ecx_l2_connection.md, docs/resources/equinix_ecx_l2_serviceprofile.md, equinix/data_source_ecx_l2_sellerprofile.go, equinix/data_source_ecx_l2_sellerprofiles.go, equinix/data_source_ecx_port.go, equinix/resource_ecx_l2_connection.go, equinix/resource_ecx_l2_serviceprofile.go
* Add deprecation messages to ecx_ terraform resources using Fabric v3 API SDK
* Add docs update for deprecated resources
=> docs: Deprecate ecx_ Terraform Resources

.github/workflows/fabric_acctest.yml, equinix/data_source_fabric_port_acc_test.go, equinix/resource_fabric_port.go
* Acceptance Tests Added for:
* `data "equinix_fabric_port"`
* `data "equinix_fabric_ports"`
* GHA added for Fabric Acceptance Tests
* Uses Two sets of Secrets for Different Tests
* Fabric Tests must be tagged PNFV or PFCR to be picked up by GHA
* Added placeholder for potential addition of sweepers
=> test: Add acceptance test for fabric_ports and GHA for fabric tests

equinix/data_source_fabric_cloud_router_acc_test.go, equinix/resource_fabric_cloud_router_acc_test.go
Includes:
- Updated resource acceptance test for FCR
- Added data source acceptance test for FCR
Note: This PR is dependent on the following pull request: (https://github.com/equinix/terraform-provider-equinix/pull/537). Refactoring will be performed after it is merged, and the changes will then be merged.
=> test: Updated resource acceptance test for FCR and added data source acceptance test for FCR

docs/resources/equinix_fabric_cloud_router.md, docs/resources/equinix_fabric_connection.md, equinix/resource_fabric_cloud_router.go
* Update Cloud Router example `package.0.code` to match recent changes in product offerings
* Fix small typo in `project` description for Cloud Router docs
* Changing in cloud router schema as well for documentation automation with TFDOCs
* Add link to Fabric Terraform Modules from Fabric Connection resource docs
=> docs: Update Fabric Docs 

equinix/resource_fabric_connection.go
- Marking provider_connection_id schema to computed in fabric_connection_resource
=> fix: Upgrading provider_connection_id schema to computed

equinix/data_source_fabric_port_acc_test.go, equinix/resource_fabric_connection_acc_test.go, go.mod, go.sum
* Equinix PDS users have different API responses that led to the following error: https://github.com/equinix/terraform-provider-equinix/issues/657
* This adds tests and upgrades the version of equinix-sdk-go to account for the missing `projectId` property on `project` responses from the API
=> test: Add tests for Panthers PDS User

docs/data-sources/equinix_fabric_cloud_router.md, docs/data-sources/equinix_fabric_connection.md, docs/data-sources/equinix_fabric_network.md, docs/data-sources/equinix_fabric_port.md, docs/data-sources/equinix_fabric_ports.md, docs/data-sources/equinix_fabric_routing_protocol.md, docs/data-sources/equinix_fabric_service_profile.md, docs/data-sources/equinix_fabric_service_profiles.md, docs/resources/equinix_fabric_cloud_router.md, docs/resources/equinix_fabric_connection.md, docs/resources/equinix_fabric_network.md, docs/resources/equinix_fabric_routing_protocol.md, docs/resources/equinix_fabric_service_profile.md
* Add getting started and API links to each data source and resource in Fabric
=> docs: Fabric docs consistency

docs/resources/equinix_network_device.md, equinix/data_source_network_device.go, equinix/resource_network_device.go
feat: To Provide Support to create BlueCat devices through terraform- BlueCat BDDS and BlueCat Edge Service Point
=> feat: To Provide Support to create BlueCat devices through terraform

docs/resources/equinix_network_device.md
feat: Update equinix_network_device.md
=> feat: Update equinix_network_device.md

internal/resources/metal/gateway/datasource.go, internal/resources/metal/gateway/datasource_test.go, internal/resources/metal/gateway/models.go, internal/resources/metal/gateway/resource.go, internal/resources/metal/gateway/resource_schema.go
This converts the metal_gateway resource and data source from packngo to equinix-sdk-go to enable the later introduction of IPv6 support.
=> feat: convert metal_gateway to equinix-sdk-go

internal/resources/metal/connection/resource.go
This issue came out of investigation into Metal acceptance test failures in which the tests appear to be failing because [a connection that was deleted came back from the API with status `deleted`](https://github.com/equinix/terraform-provider-equinix/actions/runs/9844086716/job/27176733992#step:6:2177)
> === NAME  TestAccMetalConnection_sharedVlan
>     resource_test.go:256: Error running post-test destroy, there may be dangling resources: exit status 1
>         
>         Error: Failed to delete Metal Connection 3e4601f8-5aa3-4696-bfc9-363dbb14554e
>         
>         Connection 3e4601f8-5aa3-4696-bfc9-363dbb14554e is in undexpected state
>         deleted
> --- FAIL: TestAccMetalConnection_sharedVlan (25.25s)
The metal_connection resource and data source were previously migrated from …
=> fix: convert metal_connection delete to equinix-sdk-go

docs/resources/network_device.md, equinix/data_source_network_device.go, equinix/resource_network_device.go, examples/resources/network_device/example_9.tf, templates/resources/network_device.md.tmpl
feat: PA-VM Integration with Panorama Server
Allow additional parameters in vendor config (panoramaAuthKey, panoramaIpAddress)
=> feat: PA-VM Integration with Panorama Server

equinix/resource_fabric_routing_protocol.go
Updated following Methods to fix issue for updating fabric_routing_protocol resource:
- Updated routingProtocolPayloadFromType Struct Setup
- Updated setFabricRoutingProtocolMap methods
=> fix: Updating routingProtocolPayloadFromType method by using d.Get() and updated routingProtocolMap function

internal/config/config.go
Previously, Metal and Fabric clients [used a custom retry policy](https://github.com/equinix/terraform-provider-equinix/blob/4b6af14d184c8dff4c438f42520ac2347deb6551/internal/config/config.go#L259-L280) that had extremely limited retry scenarios.  This removes the custom retry policy for those clients so that they will use the [default retry policy for the `go-retryablehttp` client](https://github.com/hashicorp/go-retryablehttp/blob/main/client.go#L495-L542).
The custom retry policy in this provider was inherited from `terraform-provider-metal`.  It was [added to that repo 5 years ago](https://github.com/equinix/terraform-provider-metal/commit/c9b838763f6ed36ac7720760039baf203d2f6f9a) to avoid retrying on 5xx errors.
For comparison, the default retry policy of `go-retryablehttp` also …
=> feat: use go-retryable's default retry policy

README.md
This PR adds a logo and fixes the broken URL
=> chore: Update Equinix Community badge

docs/resources/network_device.md, equinix/resource_network_device.go, templates/resources/network_device.md.tmpl
feat: Nfv 29975 - make ssh public key name optional in Create Virtual device request
=> feat: Nfv 29975 - make ssh public key name optional in Create Virtual device request

equinix/resource_network_device_link.go
feat: relaxing case restriction for redundancy Type.
=> feat: relaxing case restriction for redundancy Type.

equinix/resource_network_device_link.go
feat: relaxing force new for Interface ID for DLG
=> feat: relaxing force new for Interface ID for DLG

docs/resources/network_device.md, docs/resources/network_file.md, equinix/resource_network_device.go, examples/resources/equinix_network_device/aruba_edgeconnect_ha_device.tf, examples/resources/equinix_network_device/checkpoint_single_device.tf, examples/resources/equinix_network_device/cisco_ftd_cluster_znpd.tf, examples/resources/equinix_network_device/example_3.tf, examples/resources/equinix_network_device/fortigate_sdwan_single_device.tf, examples/resources/equinix_network_device/versa_sdwan_ha_device.tf, examples/resources/equinix_network_device/vyos_router_ha_device.tf, examples/resources/equinix_network_file/example_1.tf, templates/resources/network_device.md.tmpl
feat: terraform examples create device for various device types for NE
=> feat: terraform examples create device for various device types for NE

docs/resources/network_device.md, equinix/resource_network_device.go, examples/resources/equinix_network_device/infoblox_cluster_device.tf, examples/resources/equinix_network_device/infoblox_ha_device.tf, examples/resources/equinix_network_device/infoblox_single_device.tf, templates/resources/network_device.md.tmpl
feat: terraform examples create device for Infoblox Single, HA and cluster devices
=> feat: terraform examples create device for Infoblox Single, HA and cluster devices

docs/resources/network_device.md, examples/resources/equinix_network_device/infoblox_cluster_device.tf, examples/resources/equinix_network_device/infoblox_ha_device.tf, examples/resources/equinix_network_device/infoblox_single_device.tf
feat: remove hostname in infoblox create device examples
=> feat: remove hostname in infoblox create device examples

docs/data-sources/fabric_network.md, docs/resources/fabric_network.md, internal/converters/converters.go, internal/resources/fabric/network/resource_schema.go
Updated scope to use enumeration values in description along with a note for REGIONAL extra steps
=> docs: updated scope to use enumeration values in description

docs/resources/network_device.md, equinix/resource_network_device.go, equinix/resource_network_device_test.go, examples/resources/equinix_network_device/aruba_edgeconnect_ha_device_wth_purchase_order.tf, go.mod, go.sum, templates/resources/network_device.md.tmpl
feat: Purchase Order number sending part of  Secondary device in Create HA device request and added few tests for coverage.
=> feat: Purchase Order number sending part of  Secondary device in Create HA device request
